# Generated by Django 3.2.8 on 2021-10-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='Characteristics',
        ),
        migrations.AddField(
            model_name='animal',
            name='characteristics',
            field=models.ManyToManyField(to='animals.Characteristic'),
        ),
    ]
